% -------------------------------------------------------------------
%  Generated by MATLAB on 11-Dec-2024 21:34:16
%  MATLAB version: 24.2.0.2712019 (R2024b)
% -------------------------------------------------------------------
                                          

Sig = Simulink.Signal;
Sig.CoderInfo.StorageClass = 'Auto';
Sig.Description = '';
Sig.DataType = 'auto';
Sig.Min = [];
Sig.Max = [];
Sig.DocUnits = '';
Sig.Dimensions = -1;
Sig.DimensionsMode = 'auto';
Sig.Complexity = 'auto';
Sig.SampleTime = -1;
Sig.InitialValue = '';

