function hLib = tmu_optimization


hLib = RTW.TflTable;
%---------- entry: log2 ----------- 
hEnt = createCRLEntry(hLib, ...
    'double y1 = log2( double u1 )', ...
    'double y1 = ti_tmu_log_pu( double u1 )');
hEnt.setTflCFunctionEntryParameters( ...
          'Priority', 100, ...
          'ImplementationHeaderFile', 'ti_tmu_trig.h', ...
          'ImplementationHeaderPath', 'C:\ti\mcu_plus_sdk_am263px_10_00_00_35\source\mathlib\trig');



hLib.addEntry( hEnt ); 

%---------- entry: atan ----------- 
hEnt = createCRLEntry(hLib, ...
    'double y1 = atan( double u1 )', ...
    'double y1 = ti_tmu_atan( double u1 )');
hEnt.setTflCFunctionEntryParameters( ...
          'Priority', 100, ...
          'ImplementationHeaderFile', 'ti_tmu_trig.h', ...
          'ImplementationHeaderPath', 'C:\ti\mcu_plus_sdk_am263px_10_00_00_35\source\mathlib\trig');



hLib.addEntry( hEnt ); 

%---------- entry: atan2 ----------- 
hEnt = createCRLEntry(hLib, ...
    'double y1 = atan2( double u1, double u2 )', ...
    'double y1 = ti_tmu_atan2( double u1, double u2 )');
hEnt.setTflCFunctionEntryParameters( ...
          'Priority', 100, ...
          'ImplementationHeaderFile', 'ti_tmu_trig.h', ...
          'ImplementationHeaderPath', 'C:\ti\mcu_plus_sdk_am263px_10_00_00_35\source\mathlib\trig');

hEnt.EntryInfo.Algorithm = 'RTW_UNSPECIFIED';


hLib.addEntry( hEnt ); 

%---------- entry: cos ----------- 
hEnt = createCRLEntry(hLib, ...
    'double y1 = cos( double u1 )', ...
    'double y1 = ti_tmu_cos( double u1 )');
hEnt.setTflCFunctionEntryParameters( ...
          'Priority', 100, ...
          'ImplementationHeaderFile', 'ti_tmu_trig.h', ...
          'ImplementationHeaderPath', 'C:\ti\mcu_plus_sdk_am263px_10_00_00_35\source\mathlib\trig');

hEnt.EntryInfo.Algorithm = 'RTW_UNSPECIFIED';


hLib.addEntry( hEnt ); 

%---------- entry: exp ----------- 
hEnt = createCRLEntry(hLib, ...
    'double y1 = exp( double u1 )', ...
    'double y1 = ti_tmu_iexp_pu( double u1 )');
hEnt.setTflCFunctionEntryParameters( ...
          'Priority', 100, ...
          'ImplementationHeaderFile', 'ti_tmu_trig.h', ...
          'ImplementationHeaderPath', 'C:\ti\mcu_plus_sdk_am263px_10_00_00_35\source\mathlib\trig');



hLib.addEntry( hEnt ); 

%---------- entry: pow ----------- 
hEnt = createCRLEntry(hLib, ...
    'double y1 = pow( double u1, double u2 )', ...
    'double y1 = ti_tmu_powf( double u1, double u2 )');
hEnt.setTflCFunctionEntryParameters( ...
          'Priority', 100, ...
          'ImplementationHeaderFile', 'ti_tmu_trig.h', ...
          'ImplementationHeaderPath', 'C:\ti\mcu_plus_sdk_am263px_10_00_00_35\source\mathlib\trig');



hLib.addEntry( hEnt ); 

%---------- entry: sin ----------- 
hEnt = createCRLEntry(hLib, ...
    'double y1 = sin( double u1 )', ...
    'double y1 = ti_tmu_sin( double u1 )');
hEnt.setTflCFunctionEntryParameters( ...
          'Priority', 100, ...
          'ImplementationHeaderFile', 'ti_tmu_trig.h', ...
          'ImplementationHeaderPath', 'C:\ti\mcu_plus_sdk_am263px_10_00_00_35\source\mathlib\trig\');

hEnt.EntryInfo.Algorithm = 'RTW_UNSPECIFIED';


hLib.addEntry( hEnt ); 

